version: '3.8'

services:
  backend:
    container_name: 'SC-API'
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    command: python src/main.py